// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: controller.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Controller_ClientAddItem_FullMethodName     = "/controller.Controller/ClientAddItem"
	Controller_WorkerListen_FullMethodName      = "/controller.Controller/WorkerListen"
	Controller_WorkerJobComplete_FullMethodName = "/controller.Controller/WorkerJobComplete"
)

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerClient interface {
	ClientAddItem(ctx context.Context, in *AddJobRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
	WorkerListen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (Controller_WorkerListenClient, error)
	WorkerJobComplete(ctx context.Context, in *JobCompleteResponse, opts ...grpc.CallOption) (*SuccessResponse, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) ClientAddItem(ctx context.Context, in *AddJobRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, Controller_ClientAddItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) WorkerListen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (Controller_WorkerListenClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Controller_ServiceDesc.Streams[0], Controller_WorkerListen_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &controllerWorkerListenClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_WorkerListenClient interface {
	Recv() (*JobStreamResponse, error)
	grpc.ClientStream
}

type controllerWorkerListenClient struct {
	grpc.ClientStream
}

func (x *controllerWorkerListenClient) Recv() (*JobStreamResponse, error) {
	m := new(JobStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controllerClient) WorkerJobComplete(ctx context.Context, in *JobCompleteResponse, opts ...grpc.CallOption) (*SuccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, Controller_WorkerJobComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
// All implementations must embed UnimplementedControllerServer
// for forward compatibility
type ControllerServer interface {
	ClientAddItem(context.Context, *AddJobRequest) (*SuccessResponse, error)
	WorkerListen(*ListenRequest, Controller_WorkerListenServer) error
	WorkerJobComplete(context.Context, *JobCompleteResponse) (*SuccessResponse, error)
	mustEmbedUnimplementedControllerServer()
}

// UnimplementedControllerServer must be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (UnimplementedControllerServer) ClientAddItem(context.Context, *AddJobRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientAddItem not implemented")
}
func (UnimplementedControllerServer) WorkerListen(*ListenRequest, Controller_WorkerListenServer) error {
	return status.Errorf(codes.Unimplemented, "method WorkerListen not implemented")
}
func (UnimplementedControllerServer) WorkerJobComplete(context.Context, *JobCompleteResponse) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkerJobComplete not implemented")
}
func (UnimplementedControllerServer) mustEmbedUnimplementedControllerServer() {}

// UnsafeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServer will
// result in compilation errors.
type UnsafeControllerServer interface {
	mustEmbedUnimplementedControllerServer()
}

func RegisterControllerServer(s grpc.ServiceRegistrar, srv ControllerServer) {
	s.RegisterService(&Controller_ServiceDesc, srv)
}

func _Controller_ClientAddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ClientAddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_ClientAddItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ClientAddItem(ctx, req.(*AddJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_WorkerListen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).WorkerListen(m, &controllerWorkerListenServer{ServerStream: stream})
}

type Controller_WorkerListenServer interface {
	Send(*JobStreamResponse) error
	grpc.ServerStream
}

type controllerWorkerListenServer struct {
	grpc.ServerStream
}

func (x *controllerWorkerListenServer) Send(m *JobStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Controller_WorkerJobComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobCompleteResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).WorkerJobComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_WorkerJobComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).WorkerJobComplete(ctx, req.(*JobCompleteResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// Controller_ServiceDesc is the grpc.ServiceDesc for Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controller.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientAddItem",
			Handler:    _Controller_ClientAddItem_Handler,
		},
		{
			MethodName: "WorkerJobComplete",
			Handler:    _Controller_WorkerJobComplete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WorkerListen",
			Handler:       _Controller_WorkerListen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "controller.proto",
}
