[package]
name = "redis"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = { workspace = true }
anyhow = { workspace = true }
uuid = { version = "1.16.0", features = ["v4"] }
redis-lua = "0.4.0"
serde_json = { workspace = true }
serde = { workspace = true }
redis-async = "0.17.2"
